### ISSUE TITLE
Specifying both -v and --exec-cmd throws an execption and crashes

### ISSUE THREAD

**Issue by xdhmoore** [trehn/termdown#61]
I suppose with --exec-cmd you can do everything you can do with -v. Maybe it should just print out a "these flags aren't compatible" error and quit.
```
termdown -v Daniel --exec-cmd 'say hello' 10s                                    <<<
Traceback (most recent call last):
  File "/Users/frog/.local/bin/termdown", line 8, in <module>
    sys.exit(main())
  File "/Users/frog/.local/pipx/venvs/termdown/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/frog/.local/pipx/venvs/termdown/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/frog/.local/pipx/venvs/termdown/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/frog/.local/pipx/venvs/termdown/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/frog/.local/pipx/venvs/termdown/lib/python3.8/site-packages/termdown.py", line 744, in main
    curses.wrapper(countdown, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/frog/.local/pipx/venvs/termdown/lib/python3.8/site-packages/termdown.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/Users/frog/.local/pipx/venvs/termdown/lib/python3.8/site-packages/termdown.py", line 362, in countdown
    [voice_cmd, "-v", voice, annunciation.strip()],
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by JokeNeverSoke** [comment]
Technically speaking, it is possible to achieve both, but it would easily cause confusion. To workaround, either:
- Do everything in `--exec-cmd`, which would be `termdown --exec-cmd 'say hello & say {1}' 5s` or combine it into a single script
- (**Discouraged**) set `--critical` to something bigger than your time `termdown -v Daniel --exec-cmd 'say hello' 5s -c 5`
